channel: stable
addons:
  stirling_pdf:
    repository: Dula Add-on Repository/stirling_pdf
    target: stirling_pdf
  free_radius:
    repository: Dula Add-on Repository/free_radius
    target: free_radius
