channel: stable
addons:
  stirling_pdf:
    repository: Dula Add-on Repository/stirling_pdf
    target: stirling_pdf
  freeradius_oauth2_perl:
    repository: Dula Add-on Repository/freeradius_azuread
    target: freeradius_azuread
  npm:
    repository: Dula Add-on Repository/npm
    target: npm
  esphome_mcp:
    repository: Dula Add-on Repository/esphome_mcp
    target: esphome_mcp
