name: "Free radius"
version: "1.0.0"
slug: "free_radius"
description: "FreeRADIUS is a high-performance, highly configurable, and feature-rich RADIUS server."
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386